### PR TITLE
Create kubespheredev2kubesphere.yaml

### PR DESCRIPTION
**Pull request by yuswift**

### CODE REVIEW

**Comment by RolandMa1986** [comment]
I think the config is ok. But the point is wheather the Image should be synchronized from **kubespheredev** to **kubesphere** automatically.
From my perspective:
1. **kubespheredev** may not be tested even with a valid tag. 
2. The tag could be overridden in  **kubespheredev** repo

So I think we should create a manually triggered process (or triggered by tag ) for **kubespheredev** to **kubesphere** synchronization.   We can control the synchronization process.

@zryfish @pixiake, Any other ideas?

**Comment by yuswift** [comment]
Agree with your idea. We only need to sync this tag from `kubespheredev ` to `kubesphere` once. Do we have another better solution？

**Pull request merged**
